branches:
  - main
plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: feat
          release: minor
        - type: feature
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: revert
          release: minor
        - type: docs
          release: patch
        - type: style
          release: minor
        - type: chore
          release: minor
        - type: refactor
          release: patch
        - type: deps
          release: minor
        - type: deps
          scope: internal
          release: false
  - "@semantic-release/release-notes-generator"
  - - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: Features
          - type: feature
            section: Features
          - type: fix
            section: Bug Fixes
          - type: perf
            section: Performance Improvements
          - type: revert
            section: Reverts
          - type: docs
            section: Documentation
          - type: style
            section: Styles
          - type: chore
            section: Chores
          - type: deps
            section: Dependency Updates
          - type: deps
            scope: internal
            hidden: true
          - type: refactor
            section: Refactoring
          - type: test
            section: Tests
          - type: build
            section: Build System
          - type: ci
            section: Continuous Integration
  - - "@semantic-release/github"
    - releasedLabels: false
