name: Pipeline

on: [push, pull_request]

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      BATECT_CACHE_TYPE: directory
      BATECT_ENABLE_TELEMETRY: true
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Validate Batect wrapper scripts
        uses: batect/batect-wrapper-validation-action@v0.4.0

      - name: Cache Batect
        uses: actions/cache@v3.3.1
        with:
          path: ~/.batect/cache
          key: batect-${{ hashFiles('batect') }}

      - name: Cache Golang dependencies
        uses: actions/cache@v3.3.1
        with:
          path: .batect/caches/go-cache
          key: golang-${{ hashFiles('go.sum') }}
          restore-keys: |
            golang-

      - name: Download dependencies
        run: ./batect setup

      - name: Build application
        run: ./batect build

      - name: Lint code
        run: ./batect lint

      - name: Check code files have license header
        run: ./batect checkLicenseHeader

      - name: Run unit tests
        run: ./batect unitTest

  release:
    name: "Release"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'batect/services-common'
    needs:
      - build
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: Create release
        run: npx --package conventional-changelog-conventionalcommits@6.0.0 --package semantic-release@21.0.4 semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
